function Gamma = cal_Gamma_vec(x)
%%%%% 计算基于罗德里格常量进行控制的线性操作符
Gamma = [x(1), 0, 0, 0, x(3), x(2); ...
                    0, x(2), 0, x(3), 0, x(1); ...
                    0, 0, x(3), x(2), x(1), 0];
end
